-- 코드를 작성해주세요
WITH RECURSIVE RE AS (
    SELECT 1 AS N, ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT RE.N+1 AS N, D.ID
    FROM RE JOIN ECOLI_DATA AS D
    ON D.PARENT_ID = RE.ID
)
SELECT D.ID FROM RE JOIN ECOLI_DATA AS D
ON RE.ID = D.ID
WHERE RE.N = 3