-- 코드를 작성해주세요
SELECT E1.ID, 
CASE 
    WHEN (
        SELECT COUNT(*)
        FROM ECOLI_DATA AS E
        WHERE E.SIZE_OF_COLONY > E1.SIZE_OF_COLONY) < (SELECT COUNT(*) FROM ECOLI_DATA) *0.25
          THEN 'CRITICAL'
    WHEN (
        SELECT COUNT(*)
        FROM ECOLI_DATA AS E
        WHERE E.SIZE_OF_COLONY > E1.SIZE_OF_COLONY) < (SELECT COUNT(*) FROM ECOLI_DATA) *0.5
          THEN 'HIGH'
         
    WHEN (
        SELECT COUNT(*)
        FROM ECOLI_DATA AS E
        WHERE E.SIZE_OF_COLONY > E1.SIZE_OF_COLONY) < (SELECT COUNT(*) FROM ECOLI_DATA) *0.75
          THEN 'MEDIUM'
         
    ELSE 'LOW'
    END
    AS COLONY_NAME
FROM ECOLI_DATA  AS E1
ORDER BY E1.ID