-- 코드를 작성해주세요
WITH RECURSIVE GE AS (
    SELECT 
        1 AS N, 
        ID 
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT
        G.N +1 AS N,
        D.ID
    FROM ECOLI_DATA AS D JOIN GE AS G
        ON G.ID = D.PARENT_ID
)
SELECT COUNT(*) AS COUNT, N AS GENERATION
FROM GE JOIN ECOLI_DATA AS D ON GE.ID = D.ID
LEFT JOIN  ECOLI_DATA AS TEMP 
ON D.ID = TEMP.PARENT_ID
WHERE TEMP.PARENT_ID IS NULL
GROUP BY N
ORDER BY N
