-- 코드를 입력하세요

SELECT H.FLAVOR FROM FIRST_HALF AS H
RIGHT JOIN (SELECT H.SHIPMENT_ID, (SUM(J.TOTAL_ORDER)+H.TOTAL_ORDER) AS TOTAL  FROM FIRST_HALF AS H JOIN JULY AS J
ON H.FLAVOR = J.FLAVOR
GROUP BY H.FLAVOR
ORDER BY TOTAL DESC
LIMIT 3) AS T
ON T.SHIPMENT_ID = H.SHIPMENT_ID