-- 코드를 입력하세요
/*
2022-04-13
취소되지 않은 흉부외과 CS 진료 예약 내역을 조회 
*/
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD AS APNT_YMD FROM APPOINTMENT  AS A
JOIN DOCTOR AS D ON D.DR_ID = A.MDDR_ID
JOIN PATIENT AS P ON P.PT_NO = A.PT_NO
WHERE D.MCDP_CD = 'CS' AND A.APNT_CNCL_YN = 'N' AND DATE(A.APNT_YMD) = '2022-04-13'
ORDER BY APNT_YMD ASC
