-- 코드를 작성해주세요
SELECT DATA2.ID, DATA2.GENOTYPE, DATA.GENOTYPE  AS PARENT_GENOTYPE
FROM ECOLI_DATA AS DATA
JOIN ECOLI_DATA AS DATA2 
ON DATA.ID = DATA2.PARENT_ID
WHERE DATA.GENOTYPE & DATA2.GENOTYPE = DATA.GENOTYPE
ORDER BY DATA2.ID