-- 코드를 작성해주세요
SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME FROM DEVELOPERS AS D
JOIN (
SELECT CODE FROM SKILLCODES
WHERE NAME IN ('C#','Python')
) AS C
ON (D.SKILL_CODE & C.CODE) != 0
ORDER BY ID ASC