-- 코드를 작성해주세요
SELECT I.ID,D.FISH_NAME, I.LENGTH FROM FISH_INFO AS I
JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH FROM FISH_INFO
GROUP BY FISH_TYPE) AS B
ON I.FISH_TYPE = B.FISH_TYPE AND I.LENGTH = B.LENGTH
JOIN FISH_NAME_INFO AS D
ON I.FISH_TYPE = D.FISH_TYPE
ORDER BY ID ASC