-- 코드를 입력하세요
SELECT M.CATEGORY, M.MAX_PRICE, F.PRODUCT_NAME FROM FOOD_PRODUCT AS F JOIN 
(SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
 FROM FOOD_PRODUCT
 GROUP BY CATEGORY 
) AS M
ON F.CATEGORY = M.CATEGORY AND F.PRICE = M.MAX_PRICE
WHERE F.CATEGORY IN ('과자','국','김치','식용유')
ORDER BY M.MAX_PRICE DESC