-- 코드를 작성해주세요
/*
FRONT END 와 PYTHON 함께 가지고 있는
C# 가지고 있는
그외의 FRONT END
*/

WITH FE AS(SELECT CODE FROM SKILLCODES WHERE CATEGORY ='Front End'),
PY AS (SELECT CODE FROM SKILLCODES WHERE NAME ='Python'),
C AS (SELECT CODE FROM SKILLCODES WHERE NAME ='C#')


SELECT 
CASE 
    WHEN (SKILL_CODE & (SELECT CODE FROM PY)) !=0 AND EXISTS(SELECT 1 FROM FE WHERE (FE.CODE & SKILL_CODE) != 0) THEN 'A'
    WHEN SKILL_CODE & (SELECT CODE FROM C) THEN 'B'
    ELSE 'C'
    END
AS GRADE, 
ID,EMAIL FROM DEVELOPERS AS D
WHERE (SKILL_CODE & (SELECT CODE FROM C)) !=0 OR EXISTS(SELECT 1 FROM FE WHERE (FE.CODE & SKILL_CODE) != 0)
ORDER BY GRADE, ID